name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.4]
        laravel: [12.*]
        stability: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci

      - name: Execute Tests
        run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/logs/clover.xml
          fail_ci_if_error: true

      - uses: matriphe/laravel-pkg-test-action@v2
        with:
          operating_system: ubuntu-latest # The Operating System where the test runs, the default is `ubuntu-latest`
          php_version: 8.4 # The PHP version where the test runs, the default is `8.2`
          php_extensions: pdo_sqlite, sqlite3 # The PHP extension enabled for the test, separated by comma
          laravel_version: 12.* # The Laravel framework version where the test runs, the default is `^11.0`
          branch: main # The branch name, tag name, or git reference checksum to check out
          laravel_install_args: --prefer-dist # The arguments passed to Composer when installing Laravel framework, the default is `--prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins`
          package_install_args: --prefer-dist --no-progress  # The arguments passed to Composer when installing the package, the default is `--prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins`

